#!/bin/sh
# Auto-set display with config found in /etc/displayset/*.cfg files
# Licensed under GPLv3, see https://www.gnu.org/licenses/gpl-3.0.txt

[ $(ps aux | grep -v grep | grep -c "Xorg") -gt 0 ] || exit 0;

CONFIG_PATH="/etc/displayset"
FORCE=0
while [ $# -gt 0 ]; do
  case $1 in
    --cfg-path | -p ) CONFIG_PATH="${2%/}/"; shift; shift;;
    -f | --force ) FORCE=1; shift;;
    *) shift;;
  esac
done

[ -e "${CONFIG_PATH}" ] || { echo "Displayset config dir not found !"; exit 1; }

# Taken from https://github.com/codingtony/udev-monitor-hotplug
# inspired by /etc/acpd/lid.sh and the function it sources
# Filter out gdm managed display
tmp="$(ls -l /tmp/.X11-unix/* | awk '$3=="gdm"{next;}{print $NF; exit;}')"
DISPLAYNUM="${tmp##*/X}"
export DISPLAY=":${DISPLAYNUM}.0"

# from https://wiki.archlinux.org/index.php/Acpid#Laptop_Monitor_Power_Off
export XAUTHORITY=$(ps -C Xorg -f --no-header | sed -n 's/.*-auth //; s/ -[^ ].*//; p')

{ [ -z "${DISPLAY}" ] || [ -z "${XAUTHORITY}" ]; } && {
  echo "No X display found !"; exit 1;
}

CONFIGURED_OUTPUTS="";
[ $FORCE -eq 0 ] && \
	[ -e /tmp/displayset-configured-outputs ] && \
	PREVIOUS_CONFIGURED_OUTPUTS="$(cat /tmp/displayset-configured-outputs)" || PREVIOUS_CONFIGURED_OUTPUTS=""

for CONFIG in $(find "${CONFIG_PATH}" -maxdepth 1 -type f -name "*.cfg" -printf '%p '); do
  DISPLAY_OUTPUT=$(awk "/OUTPUT/{output=1; next}output==0{next}{print \$0; exit;}" ${CONFIG});
  DISPLAY_EDID=$(awk "/EDID/{edid=1; next}edid==0{next;}/^$/{exit;}{print \$1;}" ${CONFIG} | tr -d "\t\n");
  DISPLAY_ARGS=$(awk "/ARGS/{arg=1; next;}arg==0{next;}{print \$0; exit;}" ${CONFIG});
  CUSTOM_CMDS_PLUGGED=$(awk "/CUSTOM_CMDS_PLUGGED/{custom=1; next;}custom==0{next;}/^$/{exit;}{print \$0;}" ${CONFIG} | tr "\n" ";");
  CUSTOM_CMDS_UNPLUGGED=$(awk "/CUSTOM_CMDS_UNPLUGGED/{custom=1; next;}custom==0{next;}/^$/{exit;}{print \$0;}" ${CONFIG} | tr "\n" ";");

  EDID=$(xrandr --props | awk "/${DISPLAY_OUTPUT} connected/{output=1; next;}output==0{next;}/EDID:/{edid=1; next;}edid==0{next;}/[A-Zg-z]/{exit;}{print $1;}" | tr -d "\t\n");

  [ -n "${EDID}" ] && {
    # If EDID found, and not in already configured outputs, call xrandr script and custom commands
    [ "${EDID}" = "${DISPLAY_EDID}" ] && {
      [ $(expr "${PREVIOUS_CONFIGURED_OUTPUTS}" : ".*${DISPLAY_OUTPUT}${EDID}.*") -ne 0 ] && {
        CONFIGURED_OUTPUTS="${CONFIGURED_OUTPUTS}${CONFIGURED_OUTPUTS:+ }${DISPLAY_OUTPUT}${EDID}";
      } || {
        xrandr --output "${DISPLAY_OUTPUT}" ${DISPLAY_ARGS};
        [ -n "${CUSTOM_CMDS_PLUGGED}" ] && eval "${CUSTOM_CMDS_PLUGGED}"
        CONFIGURED_OUTPUTS="${CONFIGURED_OUTPUTS}${CONFIGURED_OUTPUTS:+ }${DISPLAY_OUTPUT}${EDID}";
      }
    }
  } || {
    # If no EDID found, no screen connected. Call CUSTOM_CMDS_UNPLUGGED only if OUTPUT / EDID pair is in previous configured outputs
    [ $(expr "${PREVIOUS_CONFIGURED_OUTPUTS}" : ".*${DISPLAY_OUTPUT}${DISPLAY_EDID}.*") -ne 0 ] && {
      xrandr --output "${DISPLAY_OUTPUT}" --off;
      [ -n "${CUSTOM_CMDS_UNPLUGGED}" ] && eval "${CUSTOM_CMDS_UNPLUGGED}";
    }
  }
done

echo "${CONFIGURED_OUTPUTS}" > /tmp/displayset-configured-outputs

# Copyright (C) 2020 Axel Moinet
# This program comes with ABSOLUTELY NO WARRANTY.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see https://www.gnu.org/licenses/gpl-3.0.txt for details.
