#!/bin/sh
# Auto-set display with config found in /etc/displayset/*.cfg files
# Licensed under GPLv3, see https://www.gnu.org/licenses/gpl-3.0.txt

[ $(ps aux | grep -v grep | grep -c "Xorg") -gt 0 ] || exit 0;

CONFIG_PATH="/etc/displayset"
while [ $# -gt 1 ]; do
  case $1 in
    --cfg-path | -p ) CONFIG_PATH="$2"; shift; shift;;
    *) shift;
  esac
done

[ -e "${CONFIG_PATH}" ] || { echo "Displayset config dir not found !"; exit 1; }

for CONFIG in $(find "${CONFIG_PATH}" -maxdepth 1 -type f -name "*.cfg" -printf '%p '); do
  DISPLAY_OUTPUT=$(awk "/OUTPUT/{output=1; next}output==0{next}{print \$0; exit;}" ${CONFIG});
  DISPLAY_EDID=$(awk "/EDID/{edid=1; next}edid==0{next;}/^$/{exit;}{print \$1;}" ${CONFIG} | tr -d "\t\n");
  DISPLAY_ARGS=$(awk "/ARGS/{arg=1; next;}arg==0{next;}{print \$0; exit;}" ${CONFIG});
  CUSTOM_CMDS=$(awk "/CUSTOM/{custom=1; next;}custom==0{next;}/^$/{exit;}{print \$0;}" ${CONFIG} | tr "\n" ";");

  EDID=$(xrandr --props | awk "/${DISPLAY_OUTPUT} connected/{output=1; next;}output==0{next;}/EDID:/{edid=1; next;}edid==0{next;}/[A-Zg-z]/{exit;}{print $1;}" | tr -d "\t\n");
  [ -z "${EDID}" ] && continue;

  [ "${EDID}" = "${DISPLAY_EDID}" ] && {
    xrandr --output "${DISPLAY_OUTPUT}" ${DISPLAY_ARGS}
    eval "${CUSTOM_CMDS}";
  }
done

# Copyright (C) 2020 Axel Moinet
# This program comes with ABSOLUTELY NO WARRANTY.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see https://www.gnu.org/licenses/gpl-3.0.txt for details.
